<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\BusinessActivity;
use App\Models\ServiceType;
use App\Models\SuggestedService;
use Illuminate\Database\Seeder;

class SuggestedServiceSeeder extends Seeder
{
    /**
     * Concrete services suggested per activity, GBP-style (researched 2026-09:
     * Google suggests predefined services per category — "Install faucet",
     * "Repair toilet" — editable, plus custom ones). Demand-ordered within
     * each trade; every row hangs from its TYPE, so adopting one creates a
     * Service already carrying its mould. Idempotent AND the curated source.
     */
    public function run(): void
    {
        $types = ServiceType::query()->pluck('id', 'code');

        foreach ($this->suggestions() as $activityCode => $services) {
            $activity = BusinessActivity::query()->where('code', $activityCode)->sole();
            $order = 0;

            foreach ($services as $name => $typeCode) {
                SuggestedService::query()->updateOrCreate(
                    ['business_activity_id' => $activity->id, 'name' => $name],
                    [
                        'service_type_id' => $types[$typeCode],
                        'sort_order' => ++$order,
                        'is_active' => true,
                    ],
                );
            }
        }
    }

    /**
     * @return array<string, array<string, string>> activity code => [service name => type code]
     */
    private function suggestions(): array
    {
        return [

            'panaderia' => [
                'Pan del día' => 'producto-mostrador',
                'Pan de masa madre' => 'producto-mostrador',
                'Facturas por docena' => 'producto-mostrador',
                'Sándwiches de miga' => 'pedido',
                'Torta por encargo' => 'pedido',
                'Quesos y jamones' => 'producto-mostrador',
                'Golosinas y snacks' => 'producto-mostrador',
                'Café para llevar' => 'pedido-llevar',
                'Envío a domicilio' => 'pedido-llevar',
            ],
            'pasteleria' => [
                'Torta de cumpleaños' => 'pedido',
                'Torta de bodas' => 'pedido',
                'Mesa dulce para eventos' => 'pedido',
                'Cupcakes personalizados' => 'pedido',
                'Tortas sin gluten' => 'pedido',
                'Postres individuales' => 'producto-mostrador',
                'Cookies decoradas' => 'pedido',
                'Envío a domicilio' => 'pedido-llevar',
            ],
            'restaurante' => [
                'Menú del día' => 'plato',
                'Reserva de mesa' => 'mesa',
                'Envío a domicilio' => 'pedido-llevar',
                'Pedido para llevar' => 'pedido-llevar',
                'Mesa para grupos' => 'mesa',
                'Menú sin TACC' => 'plato',
                'Menú infantil' => 'plato',
                'Parrillada para dos' => 'plato',
                'Eventos y cumpleaños' => 'presupuesto',
            ],
            'pizzeria' => [
                'Envío a domicilio' => 'pedido-llevar',
                'Pizza a la piedra' => 'plato',
                'Promo pizza + bebida' => 'combo',
                'Empanadas por docena' => 'pedido',
                'Retiro en el local' => 'pedido-llevar',
                'Pizza sin gluten' => 'plato',
                'Calzones' => 'plato',
                'Reserva de mesa' => 'mesa',
            ],
            'cafeteria' => [
                'Café para llevar' => 'pedido-llevar',
                'Desayuno completo' => 'combo',
                'Merienda para dos' => 'combo',
                'Reserva de mesa' => 'mesa',
                'Torta del día' => 'producto-mostrador',
                'Café de especialidad' => 'producto-mostrador',
                'Jugos y licuados' => 'producto-mostrador',
                'Tostados y sándwiches' => 'plato',
                'Box de desayuno sorpresa' => 'pedido',
            ],
            'rotiseria' => [
                'Envío a domicilio' => 'pedido-llevar',
                'Pollo asado' => 'pedido-llevar',
                'Milanesas por kilo' => 'pedido-llevar',
                'Menú familiar' => 'combo',
                'Guarniciones y ensaladas' => 'producto-mostrador',
                'Empanadas por docena' => 'pedido-llevar',
                'Tartas y tortillas' => 'producto-mostrador',
                'Viandas semanales' => 'pedido',
            ],
            'heladeria' => [
                'Envío a domicilio' => 'pedido-llevar',
                'Cuarto kilo de helado' => 'producto-mostrador',
                'Kilo de helado' => 'producto-mostrador',
                'Torta helada' => 'pedido',
                'Palitos y postres helados' => 'producto-mostrador',
                'Helado sin azúcar' => 'producto-mostrador',
                'Cucuruchos y vasitos' => 'producto-mostrador',
                'Helado para eventos' => 'pedido',
            ],
            'bar' => [
                'Reserva de mesa' => 'mesa',
                'Picada para compartir' => 'combo',
                'Happy hour' => 'combo',
                'Tragos de autor' => 'plato',
                'Cerveza tirada' => 'producto-mostrador',
                'Noche de música en vivo' => 'mesa',
                'Eventos privados' => 'presupuesto',
                'Barra para eventos' => 'presupuesto',
            ],
            'catering' => [
                'Catering para eventos' => 'presupuesto',
                'Catering para casamientos' => 'presupuesto',
                'Lunch empresarial' => 'pedido',
                'Coffee break' => 'pedido',
                'Mesa dulce' => 'pedido',
                'Servicio de mozos' => 'presupuesto',
                'Food truck para eventos' => 'presupuesto',
            ],

            'farmacia' => [
                'Medicamentos con receta' => 'producto-mostrador',
                'Envío a domicilio' => 'pedido',
                'Perfumería y cuidado personal' => 'producto-mostrador',
                'Dermocosmética' => 'producto-mostrador',
                'Vacunación' => 'turno',
                'Control de presión' => 'turno',
                'Pañales y maternidad' => 'producto-mostrador',
                'Test rápidos' => 'producto-mostrador',
            ],
            'consultorio-medico' => [
                'Consulta clínica' => 'consulta',
                'Control de rutina' => 'control',
                'Electrocardiograma' => 'estudio',
                'Ecografía' => 'estudio',
                'Análisis de laboratorio' => 'estudio',
                'Certificado médico' => 'consulta',
                'Apto físico' => 'consulta',
                'Consulta a domicilio' => 'consulta',
            ],
            'odontologia' => [
                'Consulta odontológica' => 'consulta',
                'Limpieza dental' => 'consulta',
                'Urgencia dental' => 'consulta',
                'Blanqueamiento' => 'consulta',
                'Ortodoncia' => 'consulta',
                'Control de ortodoncia' => 'control',
                'Implantes dentales' => 'presupuesto',
                'Prótesis dental' => 'presupuesto',
            ],
            'kinesiologia' => [
                'Sesión de kinesiología' => 'consulta',
                'Plan de 10 sesiones' => 'bono-sesiones',
                'Rehabilitación deportiva' => 'consulta',
                'Drenaje linfático' => 'consulta',
                'Masoterapia' => 'consulta',
                'RPG' => 'consulta',
                'Kinesiología a domicilio' => 'consulta',
            ],
            'psicologia' => [
                'Primera consulta psicológica' => 'consulta',
                'Sesión individual' => 'consulta',
                'Sesión online' => 'consulta',
                'Terapia de pareja' => 'consulta',
                'Terapia infantil' => 'consulta',
                'Terapia familiar' => 'consulta',
                'Orientación vocacional' => 'consulta',
            ],
            'nutricion' => [
                'Consulta nutricional' => 'consulta',
                'Plan de alimentación' => 'consulta',
                'Control mensual' => 'control',
                'Antropometría' => 'estudio',
                'Nutrición deportiva' => 'consulta',
                'Seguimiento online' => 'control',
            ],
            'laboratorio' => [
                'Análisis de sangre' => 'estudio',
                'Análisis de orina' => 'estudio',
                'Extracción a domicilio' => 'estudio',
                'Chequeo completo' => 'estudio',
                'Análisis hormonales' => 'estudio',
                'Resultados online' => 'estudio',
            ],
            'optica' => [
                'Examen visual' => 'estudio',
                'Anteojos recetados' => 'pedido',
                'Lentes de contacto' => 'producto-mostrador',
                'Lentes multifocales' => 'pedido',
                'Cristales fotocromáticos' => 'pedido',
                'Reparación de armazón' => 'arreglo',
                'Anteojos de sol' => 'producto-mostrador',
            ],

            'peluqueria' => [
                'Corte de dama' => 'turno-belleza',
                'Corte de caballero' => 'turno-belleza',
                'Color y tintura' => 'turno-belleza',
                'Balayage' => 'turno-belleza',
                'Brushing' => 'turno-belleza',
                'Alisado' => 'turno-belleza',
                'Nutrición capilar' => 'turno-belleza',
                'Peinado para eventos' => 'turno-belleza',
            ],
            'barberia' => [
                'Corte clásico' => 'turno-belleza',
                'Corte + barba' => 'turno-belleza',
                'Perfilado de barba' => 'turno-belleza',
                'Afeitado tradicional' => 'turno-belleza',
                'Corte de niños' => 'turno-belleza',
                'Diseño de cortes' => 'turno-belleza',
                'Cejas' => 'turno-belleza',
            ],
            'manicuria' => [
                'Esmaltado semipermanente' => 'turno-belleza',
                'Manicura tradicional' => 'turno-belleza',
                'Uñas esculpidas' => 'turno-belleza',
                'Pedicura' => 'turno-belleza',
                'Kapping' => 'turno-belleza',
                'Nail art' => 'turno-belleza',
                'Spa de pies' => 'turno-belleza',
                'Remoción' => 'turno-belleza',
            ],
            'centro-estetico' => [
                'Limpieza facial' => 'turno-belleza',
                'Tratamiento facial' => 'turno-belleza',
                'Masaje descontracturante' => 'turno-belleza',
                'Radiofrecuencia' => 'turno-belleza',
                'Peeling' => 'turno-belleza',
                'Lifting de pestañas' => 'turno-belleza',
                'Maderoterapia' => 'turno-belleza',
                'Plan de 5 sesiones' => 'bono-sesiones',
            ],
            'depilacion' => [
                'Depilación definitiva' => 'bono-sesiones',
                'Depilación con cera' => 'turno-belleza',
                'Piernas completas' => 'turno-belleza',
                'Cavado' => 'turno-belleza',
                'Axilas' => 'turno-belleza',
                'Rostro completo' => 'turno-belleza',
                'Depilación masculina' => 'turno-belleza',
            ],
            'spa' => [
                'Masaje relajante' => 'turno-belleza',
                'Día de spa' => 'turno-belleza',
                'Spa para dos' => 'turno-belleza',
                'Limpieza facial profunda' => 'turno-belleza',
                'Masaje con piedras calientes' => 'turno-belleza',
                'Exfoliación corporal' => 'turno-belleza',
                'Gift card de spa' => 'producto-mostrador',
            ],
            'tatuajes' => [
                'Tatuaje pequeño' => 'turno-belleza',
                'Diseño personalizado' => 'presupuesto',
                'Tatuaje a color' => 'presupuesto',
                'Cobertura de tatuaje viejo' => 'presupuesto',
                'Piercing' => 'turno-belleza',
                'Retoque de tatuaje' => 'turno-belleza',
                'Micropigmentación' => 'turno-belleza',
            ],

            'kiosco' => [
                'Golosinas y snacks' => 'producto-mostrador',
                'Bebidas frías' => 'producto-mostrador',
                'Carga virtual' => 'producto-mostrador',
                'Recarga de transporte' => 'producto-mostrador',
                'Cigarrillos' => 'producto-mostrador',
                'Helados' => 'producto-mostrador',
                'Envío a domicilio' => 'pedido',
            ],
            'almacen' => [
                'Pedido a domicilio' => 'pedido',
                'Frutas y verduras' => 'producto-mostrador',
                'Fiambres y lácteos' => 'producto-mostrador',
                'Quesos y jamones' => 'producto-mostrador',
                'Panificados' => 'producto-mostrador',
                'Bebidas y gaseosas' => 'producto-mostrador',
                'Productos de limpieza' => 'producto-mostrador',
                'Ofertas de la semana' => 'producto-mostrador',
            ],
            'supermercado' => [
                'Pedido a domicilio' => 'pedido',
                'Retiro en tienda' => 'pedido',
                'Ofertas de la semana' => 'producto-mostrador',
                'Carnicería' => 'producto-mostrador',
                'Verdulería' => 'producto-mostrador',
                'Congelados' => 'producto-mostrador',
                'Limpieza y hogar' => 'producto-mostrador',
            ],
            'dietetica' => [
                'Frutos secos' => 'producto-mostrador',
                'Productos sin TACC' => 'producto-mostrador',
                'Suplementos deportivos' => 'producto-mostrador',
                'Harinas y semillas' => 'producto-mostrador',
                'Tés e infusiones' => 'producto-mostrador',
                'Productos veganos' => 'producto-mostrador',
                'Miel y untables' => 'producto-mostrador',
                'Pedido a domicilio' => 'pedido',
            ],
            'tienda-ropa' => [
                'Consulta de talles' => 'producto-mostrador',
                'Apartado de prenda' => 'pedido',
                'Envío a domicilio' => 'pedido',
                'Cambios y devoluciones' => 'producto-mostrador',
                'Novedades de temporada' => 'producto-mostrador',
                'Calzado' => 'producto-mostrador',
                'Accesorios' => 'producto-mostrador',
                'Tarjeta de regalo' => 'producto-mostrador',
            ],
            'libreria' => [
                'Lista escolar completa' => 'pedido',
                'Fotocopias e impresiones' => 'pedido',
                'Artículos de oficina' => 'producto-mostrador',
                'Libros por encargo' => 'pedido',
                'Plastificados y anillados' => 'pedido',
                'Mochilas y cartucheras' => 'producto-mostrador',
                'Juegos didácticos' => 'producto-mostrador',
                'Regalería' => 'producto-mostrador',
            ],
            'ferreteria' => [
                'Consulta de stock' => 'producto-mostrador',
                'Copia de llaves' => 'producto-mostrador',
                'Envío a domicilio' => 'pedido',
                'Materiales eléctricos' => 'producto-mostrador',
                'Pinturas' => 'producto-mostrador',
                'Artículos de plomería' => 'producto-mostrador',
                'Herramientas eléctricas' => 'producto-mostrador',
                'Riego y jardín' => 'producto-mostrador',
            ],
            'electronica' => [
                'Accesorios de celular' => 'producto-mostrador',
                'Service técnico' => 'arreglo',
                'Cambio de pantalla' => 'arreglo',
                'Cambio de batería' => 'arreglo',
                'Consulta de stock' => 'producto-mostrador',
                'Fundas y vidrios templados' => 'producto-mostrador',
                'Auriculares y parlantes' => 'producto-mostrador',
                'Consolas y videojuegos' => 'producto-mostrador',
            ],
            'floreria' => [
                'Ramo a domicilio' => 'pedido',
                'Arreglo floral' => 'pedido',
                'Desayunos sorpresa' => 'pedido',
                'Ramo de novia' => 'presupuesto',
                'Flores para eventos' => 'presupuesto',
                'Coronas fúnebres' => 'pedido',
                'Suscripción semanal de flores' => 'abono-mensual',
                'Plantas de interior' => 'producto-mostrador',
            ],

            'hotel' => [
                'Reserva de habitación' => 'reserva-habitacion',
                'Habitación matrimonial' => 'reserva-habitacion',
                'Habitación familiar' => 'reserva-habitacion',
                'Desayuno incluido' => 'reserva-habitacion',
                'Late check-out' => 'reserva-habitacion',
                'Day use' => 'reserva-habitacion',
                'Traslado al aeropuerto' => 'traslado',
                'Salón para eventos' => 'presupuesto',
            ],
            'agencia-viajes' => [
                'Paquete de vacaciones' => 'presupuesto',
                'Excursión guiada' => 'excursion',
                'Pasajes aéreos' => 'presupuesto',
                'Cruceros' => 'presupuesto',
                'Viaje de egresados' => 'presupuesto',
                'Seguro de viaje' => 'presupuesto',
                'Alquiler de auto' => 'presupuesto',
                'Asistencia al viajero' => 'presupuesto',
            ],
            'excursiones' => [
                'City tour' => 'excursion',
                'Excursión de día completo' => 'excursion',
                'Salida de trekking' => 'excursion',
                'Paseo en barco' => 'excursion',
                'Cabalgatas' => 'excursion',
                'Salida de pesca' => 'excursion',
                'Excursión privada' => 'excursion',
            ],
            'traslados' => [
                'Traslado al aeropuerto' => 'traslado',
                'Viaje a larga distancia' => 'traslado',
                'Remis por hora' => 'traslado',
                'Traslado para eventos' => 'traslado',
                'Traslado corporativo' => 'traslado',
                'Chofer por día' => 'traslado',
                'Mensajería y encomiendas' => 'pedido',
            ],

            'apoyo-escolar' => [
                'Clases de matemática' => 'clase-particular',
                'Clases de lengua' => 'clase-particular',
                'Clases de física y química' => 'clase-particular',
                'Clases de inglés' => 'clase-particular',
                'Preparación de exámenes' => 'clase-particular',
                'Técnicas de estudio' => 'clase-particular',
                'Apoyo universitario' => 'clase-particular',
                'Apoyo en verano' => 'curso',
            ],
            'instituto-idiomas' => [
                'Curso de inglés' => 'curso',
                'Curso de portugués' => 'curso',
                'Clase particular de idioma' => 'clase-particular',
                'Curso para niños' => 'curso',
                'Preparación de exámenes internacionales' => 'curso',
                'Conversación con nativos' => 'clase-grupal',
                'Curso intensivo de verano' => 'curso',
                'Clases para empresas' => 'presupuesto',
            ],
            'academia-musica' => [
                'Clases de guitarra' => 'clase-particular',
                'Clases de piano' => 'clase-particular',
                'Clases de canto' => 'clase-particular',
                'Clases de batería' => 'clase-particular',
                'Clases online' => 'clase-particular',
                'Taller grupal' => 'clase-grupal',
                'Sala de ensayo' => 'alquiler-equipo',
            ],
            'jardin-infantes' => [
                'Visita guiada y vacantes' => 'turno',
                'Sala maternal' => 'curso',
                'Jardín de jornada completa' => 'curso',
                'Jardín de media jornada' => 'curso',
                'Extensión horaria' => 'curso',
                'Taller de verano' => 'curso',
                'Colonia de vacaciones' => 'curso',
            ],
            'autoescuela' => [
                'Curso de manejo' => 'curso',
                'Clase individual de manejo' => 'clase-particular',
                'Preparación para el examen' => 'clase-particular',
                'Clases de perfeccionamiento' => 'clase-particular',
                'Curso de moto' => 'curso',
                'Manejo defensivo' => 'curso',
                'Trámite de licencia' => 'presupuesto',
            ],

            'inmobiliaria' => [
                'Visita a la propiedad' => 'visita-propiedad',
                'Tasación de propiedad' => 'tasacion',
                'Propiedades en alquiler' => 'visita-propiedad',
                'Propiedades en venta' => 'visita-propiedad',
                'Vender mi propiedad' => 'tasacion',
                'Alquileres comerciales' => 'visita-propiedad',
                'Alquiler temporario' => 'alquiler-temporario',
                'Créditos hipotecarios' => 'presupuesto',
            ],
            'administracion-alquileres' => [
                'Administración de alquiler' => 'presupuesto',
                'Tasación de alquiler' => 'tasacion',
                'Contratos de alquiler' => 'presupuesto',
                'Cobranza de alquileres' => 'presupuesto',
                'Seguro de caución' => 'presupuesto',
                'Alquiler temporario' => 'alquiler-temporario',
            ],

            'lavanderia' => [
                'Lavado y secado' => 'arreglo',
                'Lavado por kilo' => 'arreglo',
                'Lavado de acolchados' => 'arreglo',
                'Planchado' => 'arreglo',
                'Tintorería' => 'arreglo',
                'Lavado de zapatillas' => 'arreglo',
                'Retiro a domicilio' => 'pedido',
            ],
            'cerrajeria' => [
                'Urgencia las 24 horas' => 'arreglo',
                'Apertura de puerta' => 'arreglo',
                'Apertura de autos' => 'arreglo',
                'Cambio de cerradura' => 'arreglo',
                'Copia de llaves' => 'producto-mostrador',
                'Llave codificada de auto' => 'arreglo',
                'Cerraduras electrónicas' => 'presupuesto',
            ],
            'limpieza' => [
                'Limpieza de hogar' => 'visita-presupuesto',
                'Limpieza de oficinas' => 'presupuesto',
                'Limpieza final de obra' => 'visita-presupuesto',
                'Limpieza de alfombras' => 'arreglo',
                'Desinfección' => 'visita-presupuesto',
                'Limpieza de tanques de agua' => 'presupuesto',
                'Limpieza de vidrios en altura' => 'presupuesto',
            ],
            'mudanzas' => [
                'Mudanza dentro de la ciudad' => 'visita-presupuesto',
                'Mudanza a larga distancia' => 'visita-presupuesto',
                'Mini flete' => 'presupuesto',
                'Flete por hora' => 'presupuesto',
                'Servicio de embalaje' => 'presupuesto',
                'Guardamuebles' => 'presupuesto',
            ],
            'imprenta' => [
                'Tarjetas personales' => 'pedido',
                'Folletos y volantes' => 'pedido',
                'Impresión de banners' => 'pedido',
                'Estampado de remeras' => 'pedido',
                'Etiquetas y stickers' => 'pedido',
                'Invitaciones de eventos' => 'pedido',
                'Talonarios y facturas' => 'pedido',
                'Sellos personalizados' => 'pedido',
            ],
            'fotografia' => [
                'Sesión de fotos' => 'turno',
                'Cobertura de eventos' => 'presupuesto',
                'Book de fotos' => 'turno',
                'Fotos de recién nacidos' => 'turno',
                'Fotos de producto' => 'presupuesto',
                'Video de eventos' => 'presupuesto',
                'Impresión de fotos' => 'pedido',
            ],
            'eventos' => [
                'Organización integral' => 'presupuesto',
                'Ambientación de eventos' => 'presupuesto',
                'Alquiler de livings' => 'alquiler-equipo',
                'DJ e iluminación' => 'presupuesto',
                'Catering' => 'presupuesto',
                'Búsqueda de salón' => 'presupuesto',
                'Coordinación del día' => 'presupuesto',
            ],
            'reparacion-electrodomesticos' => [
                'Reparación de lavarropas' => 'arreglo',
                'Reparación de heladera' => 'arreglo',
                'Reparación de microondas' => 'arreglo',
                'Reparación de televisores' => 'arreglo',
                'Service de aire acondicionado' => 'arreglo',
                'Instalación de aire acondicionado' => 'visita-presupuesto',
                'Visita a domicilio' => 'visita-presupuesto',
                'Repuestos de electrodomésticos' => 'producto-mostrador',
            ],

            'estudio-contable' => [
                'Monotributo' => 'presupuesto',
                'Liquidación de sueldos' => 'presupuesto',
                'Impuestos y declaraciones' => 'presupuesto',
                'Alta de empresas y sociedades' => 'presupuesto',
                'Certificaciones contables' => 'presupuesto',
                'Moratorias y planes de pago' => 'presupuesto',
                'Consulta contable' => 'turno',
            ],
            'estudio-juridico' => [
                'Consulta legal' => 'turno',
                'Sucesiones' => 'presupuesto',
                'Redacción de contratos' => 'presupuesto',
                'Divorcios' => 'presupuesto',
                'Despidos y reclamos laborales' => 'presupuesto',
                'Accidentes de tránsito' => 'presupuesto',
                'Amparos de salud' => 'presupuesto',
            ],
            'arquitectura' => [
                'Proyecto de obra' => 'presupuesto',
                'Dirección de obra' => 'presupuesto',
                'Remodelación' => 'visita-presupuesto',
                'Refacción de baños y cocinas' => 'visita-presupuesto',
                'Diseño de interiores' => 'presupuesto',
                'Planos y habilitaciones' => 'presupuesto',
                'Render y maquetas' => 'presupuesto',
            ],
            'seguros' => [
                'Seguro de auto' => 'presupuesto',
                'Seguro de moto' => 'presupuesto',
                'Seguro de hogar' => 'presupuesto',
                'Seguro de vida' => 'presupuesto',
                'Seguro para comercios' => 'presupuesto',
                'Seguro de mascotas' => 'presupuesto',
                'Cotización de póliza' => 'presupuesto',
            ],
            'agencia-marketing' => [
                'Manejo de redes' => 'presupuesto',
                'Campañas publicitarias' => 'presupuesto',
                'Publicidad online' => 'presupuesto',
                'Diseño de marca' => 'presupuesto',
                'Página web' => 'presupuesto',
                'Fotografía de producto' => 'presupuesto',
                'Email marketing' => 'presupuesto',
            ],
            'desarrollo-software' => [
                'Desarrollo a medida' => 'presupuesto',
                'Página web' => 'presupuesto',
                'Tienda online' => 'presupuesto',
                'App móvil' => 'presupuesto',
                'Sistemas de gestión' => 'presupuesto',
                'Chatbots e IA' => 'presupuesto',
                'Soporte y mantenimiento' => 'presupuesto',
            ],

            'gimnasio' => [
                'Abono mensual' => 'abono-mensual',
                'Clases grupales' => 'clase-grupal',
                'Funcional' => 'clase-grupal',
                'Spinning' => 'clase-grupal',
                'Pase diario' => 'turno',
                'Plan trimestral' => 'abono-mensual',
                'Plan familiar' => 'abono-mensual',
                'Rutina personalizada' => 'turno',
            ],
            'yoga' => [
                'Clase de yoga' => 'clase-grupal',
                'Clase de prueba' => 'clase-grupal',
                'Abono mensual' => 'abono-mensual',
                'Yoga para embarazadas' => 'clase-grupal',
                'Meditación' => 'clase-grupal',
                'Yoga en empresas' => 'presupuesto',
            ],
            'pilates' => [
                'Clase en reformer' => 'clase-grupal',
                'Clase de prueba' => 'clase-grupal',
                'Sesión individual' => 'turno',
                'Abono mensual' => 'abono-mensual',
                'Pack de 8 clases' => 'bono-sesiones',
                'Pilates terapéutico' => 'clase-grupal',
            ],
            'natacion' => [
                'Clases para niños' => 'clase-grupal',
                'Clases para adultos' => 'clase-grupal',
                'Matronatación' => 'clase-grupal',
                'Abono mensual' => 'abono-mensual',
                'Aquagym' => 'clase-grupal',
                'Pileta libre' => 'turno',
            ],
            'entrenador-personal' => [
                'Entrenamiento personalizado' => 'turno',
                'Plan de 8 sesiones' => 'bono-sesiones',
                'Entrenamiento a domicilio' => 'turno',
                'Entrenamiento online' => 'turno',
                'Rutina + seguimiento mensual' => 'abono-mensual',
            ],
            'alquiler-canchas' => [
                'Cancha de fútbol 5' => 'alquiler-equipo',
                'Cancha de pádel' => 'alquiler-equipo',
                'Cancha de tenis' => 'alquiler-equipo',
                'Turno fijo semanal' => 'abono-mensual',
                'Escuelita de fútbol' => 'clase-grupal',
                'Cumpleaños deportivos' => 'presupuesto',
                'Torneos' => 'presupuesto',
            ],

            'veterinaria' => [
                'Consulta veterinaria' => 'consulta',
                'Vacunación' => 'control',
                'Atención de urgencia' => 'consulta',
                'Castración' => 'consulta',
                'Desparasitación' => 'control',
                'Análisis clínicos' => 'estudio',
                'Ecografías' => 'estudio',
                'Cirugías' => 'presupuesto',
            ],
            'peluqueria-canina' => [
                'Baño y corte' => 'turno-belleza',
                'Corte de raza' => 'turno-belleza',
                'Corte de uñas' => 'turno-belleza',
                'Deslanado' => 'turno-belleza',
                'Baño antipulgas' => 'turno-belleza',
                'Higiene de oídos' => 'turno-belleza',
                'Retiro y entrega a domicilio' => 'pedido',
            ],
            'petshop' => [
                'Alimento balanceado' => 'producto-mostrador',
                'Alimento medicado' => 'producto-mostrador',
                'Envío a domicilio' => 'pedido',
                'Accesorios y juguetes' => 'producto-mostrador',
                'Arena para gatos' => 'producto-mostrador',
                'Peceras y acuarismo' => 'producto-mostrador',
                'Ropa para mascotas' => 'producto-mostrador',
            ],
            'guarderia-mascotas' => [
                'Guardería por día' => 'turno',
                'Alojamiento por noche' => 'turno',
                'Colonia de día' => 'turno',
                'Paseos semanales' => 'abono-mensual',
                'Adiestramiento' => 'turno',
                'Transporte de mascotas' => 'pedido',
            ],

            'taller-mecanico' => [
                'Service completo' => 'arreglo',
                'Cambio de aceite' => 'arreglo',
                'Arreglo de frenos' => 'arreglo',
                'Embrague' => 'presupuesto',
                'Correa de distribución' => 'presupuesto',
                'Carga de aire acondicionado' => 'arreglo',
                'Diagnóstico computarizado' => 'turno',
                'Tren delantero y suspensión' => 'presupuesto',
            ],
            'lavadero-autos' => [
                'Lavado completo' => 'turno',
                'Lavado premium' => 'turno',
                'Limpieza de tapizados' => 'turno',
                'Lavado de motor' => 'turno',
                'Encerado y pulido' => 'turno',
                'Tratamiento cerámico' => 'presupuesto',
            ],
            'gomeria' => [
                'Reparación de cubierta' => 'arreglo',
                'Cambio de neumáticos' => 'arreglo',
                'Cubiertas nuevas y usadas' => 'producto-mostrador',
                'Balanceo y alineación' => 'arreglo',
                'Reparación de llantas' => 'arreglo',
                'Rotación de cubiertas' => 'arreglo',
                'Auxilio de goma' => 'arreglo',
            ],
            'repuestos' => [
                'Consulta de repuesto' => 'presupuesto',
                'Repuestos originales' => 'producto-mostrador',
                'Baterías de auto' => 'producto-mostrador',
                'Lubricantes y filtros' => 'producto-mostrador',
                'Accesorios y luces' => 'producto-mostrador',
                'Búsqueda de repuestos difíciles' => 'presupuesto',
                'Envío a domicilio' => 'pedido',
            ],
            'concesionaria' => [
                'Test drive' => 'turno',
                'Ver usados disponibles' => 'turno',
                'Cotización de usado' => 'presupuesto',
                'Planes de financiación' => 'presupuesto',
                'Turno de service' => 'turno',
                'Accesorios originales' => 'producto-mostrador',
            ],

            'otra-actividad' => [
                'Turno' => 'turno',
                'Pedido' => 'pedido',
                'Presupuesto' => 'presupuesto',
                'Consulta' => 'turno',
                'Envío a domicilio' => 'pedido',
            ],

        ];
    }
}
