<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Comment debt — files still holding Spanish or oversized comments
|--------------------------------------------------------------------------
| A TO-DO list, not an exemption: every entry has to disappear. The guardian
| only tolerates what is listed here, so nothing new can slip in while the
| backlog is worked through. NEVER add a path: fix the file instead.
|
| Rule: .ai/guidelines/comentarios.md
*/

return [
    'resources/views/auth/login.blade.php',
    'resources/views/components/catalog/form-row.blade.php',
    'resources/views/components/catalog/form-shell.blade.php',
    'resources/views/components/catalog/master.blade.php',
    'resources/views/components/catalog/table.blade.php',
    'resources/views/components/catalog/toolbar.blade.php',
    'resources/views/components/catalog/⚡business-activity.blade.php',
    'resources/views/components/catalog/⚡business-sector.blade.php',
    'resources/views/components/catalog/⚡country.blade.php',
    'resources/views/components/catalog/⚡currency.blade.php',
    'resources/views/components/catalog/⚡manager.blade.php',
    'resources/views/components/catalog/⚡province.blade.php',
    'resources/views/components/catalog/⚡region.blade.php',
    'resources/views/components/catalog/⚡service-attribute.blade.php',
    'resources/views/components/catalog/⚡service-modality.blade.php',
    'resources/views/components/catalog/⚡service-type.blade.php',
    'resources/views/components/catalog/⚡social-network.blade.php',
    'resources/views/components/catalog/⚡status.blade.php',
    'resources/views/components/catalog/⚡tax-condition.blade.php',
    'resources/views/components/configuration/⚡company.blade.php',
    'resources/views/components/inputsform/combobox.blade.php',
    'resources/views/components/inputsform/input.blade.php',
    'resources/views/components/inputsform/select.blade.php',
    'resources/views/components/inputsform/switch-field.blade.php',
    'resources/views/components/layouts/marketing.blade.php',
    'resources/views/components/site/footer.blade.php',
    'resources/views/components/site/hero.blade.php',
    'resources/views/components/site/navbar.blade.php',
    'resources/views/components/ui/stepper.blade.php',
    'resources/views/components/ui/tabs.blade.php',
    'resources/views/components/⚡dialog.blade.php',
    'resources/views/layouts/app.blade.php',
    'resources/views/layouts/guest.blade.php',
    'tests/Browser/CatalogBusinessMastersBrowserTest.php',
    'tests/Browser/CatalogCurrencyEditBrowserTest.php',
    'tests/Browser/CatalogNewMastersBrowserTest.php',
    'tests/Browser/CatalogRailSearchBrowserTest.php',
    'tests/Browser/CatalogTableLayoutBrowserTest.php',
    'tests/Browser/ConfigurationCompanyBrowserTest.php',
    'tests/Feature/Api/AuthTest.php',
    'tests/Feature/Auth/LoginViewTest.php',
    'tests/Feature/Auth/RegistrationTest.php',
    'tests/Feature/BaseFormTest.php',
    'tests/Feature/BroadcastChannelTest.php',
    'tests/Feature/BusinessActivitiesPivotTest.php',
    'tests/Feature/BusinessActivityTest.php',
    'tests/Feature/BusinessAuditTest.php',
    'tests/Feature/BusinessCatalogSeederTest.php',
    'tests/Feature/CatalogBusinessActivityTest.php',
    'tests/Feature/CatalogBusinessActivityUpdateTest.php',
    'tests/Feature/CatalogCountryTest.php',
    'tests/Feature/CatalogCountryUpdateTest.php',
    'tests/Feature/CatalogCurrencyTest.php',
    'tests/Feature/CatalogCurrencyUpdateTest.php',
    'tests/Feature/CatalogEditorPathTest.php',
    'tests/Feature/CatalogManagerTest.php',
    'tests/Feature/CatalogOptionsTest.php',
    'tests/Feature/CatalogProvinceTest.php',
    'tests/Feature/CatalogProvinceUpdateTest.php',
    'tests/Feature/CatalogRegionTest.php',
    'tests/Feature/CatalogServiceAttributeTest.php',
    'tests/Feature/CatalogServiceTypeTest.php',
    'tests/Feature/CatalogSocialNetworkTest.php',
    'tests/Feature/CatalogStatusTest.php',
    'tests/Feature/ConfigurationCompanyTest.php',
    'tests/Feature/CurrencyActivityLogTest.php',
    'tests/Feature/DestructiveCommandGuardTest.php',
    'tests/Feature/GoldenRulesFormLayoutTest.php',
    'tests/Feature/LivewirePersistentMiddlewareTest.php',
    'tests/Feature/LocaleTest.php',
    'tests/Feature/NavigationTest.php',
    'tests/Feature/NotificationServiceTest.php',
    'tests/Feature/TableDensityTest.php',
    'tests/Feature/TaxConditionSeederTest.php',
    'tests/Feature/UiComponentsTest.php',
    'tests/TestCase.php',
    'tests/Unit/CountryDtoTest.php',
];
